version: "0.2"

env:
  variables:
    AWS_ACCOUNT_ID: "675045716830"
    REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t image-emoji .
      - docker images
  post_build:
    commands:
      - echo Tagging and pushing the Docker image...
      - docker tag image-emoji $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/repo-emoji-gen:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/repo-emoji-gen:latest
      - echo Writing imagedefinitions.json...
      - echo "[{\"name\":\"$ImageName\",\"imageUri\":\"$AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/repo-emoji-gen:latest\"}]" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json